name: dumble_audio
description: Plugin for connecting dumble to native audio system

publish_to: 'none'

version: 0.4.2

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: eu.epnw.dumble_audio
        pluginClass: DumbleAudioPlugin
      ios:
        pluginClass: DumbleAudioPlugin